### ISSUE TITLE
collapseDegCreToGene function

### ISSUE THREAD

**Issue by tjv16** [brianSroberts/DegCre#1]
When I try to run the collapseDegCreToGene() function, I get this error message:
"Error: unable to find an inherited method for function 'mcols' for signature 'x="NULL"'

degCreListY <- collapseDegCreToGene(listDegCreList,
                                    method = "nearest",
                                    geneColname = "GeneSymb",
                                    useParallel=TRUE)

but when I check listDegCreList$min30$DegGR$GeneSymb there are 28762 gene names present.

**Comment by brianSroberts** [comment]
Looks like you are giving it a list of degResList. It's expecting one degResList.
